# Generated by Django 5.0.1 on 2024-01-02 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creatrd_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
